### ISSUE TITLE
Dom Collab

### ISSUE THREAD

**Issue by domfarolino** [emilyjianmarie/portfolio2016#2]
Heyyyy :) If you'd like to add me as a collaborator I can make changes that get approved by you on the repository so I don't have to fork the repository (make my own copy more-or-less).

To do this you can hit the settings button in the bar above the repository:
<img width="228" alt="screen shot 2017-08-01 at 4 48 55 pm" src="https://user-images.githubusercontent.com/9669289/28851749-9f8f8166-76d9-11e7-985d-5d4c3a3da6dd.png">

And then in that menu you can hit the "collaborators" button on the left there.

<img width="276" alt="screen shot 2017-08-01 at 4 49 03 pm" src="https://user-images.githubusercontent.com/9669289/28851751-a130b814-76d9-11e7-829a-2e57bea8cbb9.png">

That gives you a search bar in which you can search me (HMU FAM) and I can get an invitation/accept/collab with you!

**Comment by emilyjianmarie** [comment]
hi
